### ISSUE TITLE
State change listener

### ISSUE THREAD

**Issue by biddster** [vinaygaba/CreditCardView#12]
It would be great if we could have some kind of state change listener which fires after all of the CreditCardView's internal text changed processing has taken place. 

This would allow client code to update models and validate the current state of the card entry (i.e. valid enables a button).

**Comment by vinaygaba** [comment]
@biddster I really like this idea! Can u give me certain scenarios where this should fire. Should it fire only when all the values are entered ? Or is there something else you are looking at?

**Comment by biddster** [comment]
I'm thinking of the edit scenario. If the user starts changing the expiry date to something invalid, I think I would want to know immediately so that I can disable an update button. What do you think?

**Comment by vinaygaba** [comment]
I'm thinking on the lines of how generic could these invalid conditions be. Or is it something that should be customizable by the users of this library. Putting some thought behind this.

**Comment by biddster** [comment]
I suspect that's something the library users would want to decide. Perhaps we just have a listener like this?

```
interface CreditCardListener {
    void onCardNumberChanged();
    void onCardHolderChanged();
    void onExpiryDateChange();
    void onCvvChanged();
}
```

Would that suffice for most folks? I think it would for me.

**Comment by vinaygaba** [comment]
Yes that way he let the developer handle whatever checks/validation/etc the might want to do. This makes sense and could be very useful. Will try to complete this today!

**Comment by biddster** [comment]
I forgot to mention that I believe it's possible to directly reference the fields in the view. So one could actually add their own text changed listeners.

**Comment by vinaygaba** [comment]
Ah! Does it make this issue irrelevant? I mean is it even needed now?

**Comment by biddster** [comment]
Let me report back and I'll see how well it works. If it's workable, I'll close.

**Comment by vinaygaba** [comment]
Great! Thanks!

**Comment by biddster** [comment]
Seems to work fine, perfectly workable. Closing.

**Comment by vinaygaba** [comment]
Awesome!
