### ISSUE TITLE
1.0.3 declared but getting code inconsistent with (older than) release commit

### ISSUE THREAD

**Issue by josefdlange** [vinaygaba/CreditCardView#19]
It's all in the title. I have `jitpack` declared as the very first repo to look in for dependencies, I've cleared every possible cache, and yet I still get a `jar` of the library that has old code -- even though the `jar` has `1.0.3` in the name, things like programmatic setters do not update the views.

**Comment by josefdlange** [comment]
Oh thank god. Added `mavenCentral()` to my `repositories` and it picked up the right one. So I guess there are two builds out in the world calling themselves `1.0.3`? I'd say release a new version that's literally just a version bump, so that this doesn't happen to people. Closing the issue.

**Comment by KgotsoK** [comment]
This is so frustrating - can't seem to get the right package.
