### ISSUE TITLE
Font problem

### ISSUE THREAD

**Issue by ragaisis** [vinaygaba/CreditCardView#20]
Lithuanian letters are not supported in this font 😞 
ąčęėįšųūž ĄČĘĖĮŠŲŪŽ

Could you please add update with possibility to change font to standart?

**Comment by safaorhan** [comment]
Same problem here. I personally want to customize the font and make it fit the rest of the design.

Besides Turkish characters are not supported with the default font of library: ĞŞÜİ

**Comment by vinaygaba** [comment]
I have not worked on this library since a while but I assure you, I will be releasing a new version in the next couple of weeks and will be adding features and fixing a bunch of issues.

**Comment by vinaygaba** [comment]
This issue has been resolved by the referenced PR. Will be pushing it as part of 1.0.4
