### ISSUE TITLE
Does Not display programmatically

### ISSUE THREAD

**Issue by bktowett** [vinaygaba/CreditCardView#21]
Hello,
The library works fine when the data is put in xml but does not work when I want to put values from java side. Please help

**Comment by vinaygaba** [comment]
@bktowett Hey the library works fine even when the fields are populated programmatically? Can you give me more context ? It could be some other issue. What version of the library are u using?

**Comment by bktowett** [comment]
@vinaygaba here is my gradle config

`apply plugin: 'com.android.application'
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"
    defaultConfig {
        applicationId "com.ceva.codevinci.creditcard"
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.vinaygaba:creditcardview:1.0.3'
}`

this is my xml
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.ceva.codevinci.creditcard.MainActivity">
    <com.vinaygaba.creditcardview.CreditCardView
        android:id="@+id/card1"
        android:layout_width="fill_parent"
        android:layout_height="225dp"
        android:background="@drawable/cardbackground_world"
        android:layout_marginBottom="16dp"
        android:layout_marginTop="16dp"
        app:cardNumberTextColor="#cccccc"
        app:cardNumberFormat="masked_all_but_last_four"
        app:cardNameTextColor="#cccccc"
        app:type="auto"
        app:brandLogo="@drawable/brandlogo"
        app:putChip="true"
        app:expiryDate = "02/22"
        app:expiryDateTextColor="#cccccc"
        app:isEditable="false"
        app:validTillTextColor="#cccccc"
        app:hintTextColor = "#cccccc"
        />
</RelativeLayout>
`

Finally, here is my activity

`public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        CreditCardView creditCardView2= new CreditCardView(this);
        creditCardView2.setCardNumber("4444444444444444");
        creditCardView2.setCardName("CODEVINCI LEONARDO");
        creditCardView2.setIsEditable(false);
    }`

**Comment by vinaygaba** [comment]
@bktowett Can you try changing the last line to the following:

```
creditCardView2.setIsEditable(true);
```

**Comment by bktowett** [comment]
@vinaygaba I appreciate your very quick responses. Sadly, it still doesn't work after your suggestions.
