### ISSUE TITLE
creditcard.ttf and creditcard2.ttf are not redistributable

### ISSUE THREAD

**Issue by tadfisher** [vinaygaba/CreditCardView#4]
These files are located here: https://github.com/vinaygaba/CreditCardView/tree/master/library/src/main/assets/fonts

This typeface was created by and is available under license from K-Type: http://www.k-type.com/fonts/credit-card/

Their license terms do not permit redistribution in open-source projects: http://www.k-type.com/licences/

**Comment by vinaygaba** [comment]
Hi Tad,
Thanks for pointing this out. I did not notice this before. Although creditcard.tff is the font you are talking about, the second one is an alternate file that I had renamed for convenience. I am going to look into finding out which font I was using and check its license and replace it with a font that permits us in using it in an open source library. Thank you.

**Comment by vinaygaba** [comment]
Also, the link you shared shows that the font is free for personal use and need us to take a commercial license for any commercial use. Since this is not for a commercial purpose, would I still need require commercial version?

**Comment by vinaygaba** [comment]
But I also get your point that developers would be using it in apps which have a commercial purpose. Do you have any recommendations for any alternatives to this font?

**Comment by tadfisher** [comment]
You could negotiate a custom license with K-Type. Alternatively, Kredit is a free OCR-style typeface that would be suitable, if not exactly what card embossers use: http://www.fontspring.com/fonts/typodermic/kredit

**Comment by vinaygaba** [comment]
I license on desktops for Kredit is free but for Apps, its $240!

**Comment by vinaygaba** [comment]
What do you think about [Halter](http://www.dafont.com/font.php?file=halter&page=1&nb_ppp_old=10&text=CREDIT+CARD&nb_ppp=10&psize=m&classt=alpha)

**Comment by vinaygaba** [comment]
I've made the change to Halter, which is free for personal and commercial use and is quite similar to the font I was using. Will be closing the issue. Thank you for pointing this out! Appreciate it
