### ISSUE TITLE
Code Style Guidelines

### ISSUE THREAD

**Issue by VenomVendor** [vinaygaba/CreditCardView#9]
Strictly follow [Code Style Guidelines](https://source.android.com/source/code-style.html)  for further contribution.

**Comment by vinaygaba** [comment]
I certainly have formatting and cleaning the code on my agenda for the forthcoming release. Thank you for the link. Will strictly enforce it :)

**Comment by vinaygaba** [comment]
Hi @VenomVendor,
I have tried to enforce the suggestions and have formatted some of the code. Would appreciate if you could take a look and point out additional recommendations if any :) Appreciate your contribution. Thank you!

**Comment by VenomVendor** [comment]
[Updated code with pull request.](https://github.com/vinaygaba/CreditCardView/pull/10)

**Comment by vinaygaba** [comment]
Hi @VenomVendor,
This is excellent! I have learnt so many new things by just analyzing the formatting you did! I just had one question, which is if you are able to see the layout correctly in the activity_main file of the sample project. I am getting some new errors in the preview screen. Wanted to know if you were seeing the same thing.

**Comment by VenomVendor** [comment]
Yes, I tested against sample project.
Can you tell what exactly is the error?

**Comment by vinaygaba** [comment]
Nevermind, looks like a bug in Android Studio. Restart, Build, Clean seems to have solved it!

**Comment by vinaygaba** [comment]
It was an error in the layout preview screen, on the lines of cannot resolve resource and pointing to the layout inflater line.

**Comment by VenomVendor** [comment]
Can you accept the merge & close.

**Comment by vinaygaba** [comment]
Yes doing just that. In a  minute :)

**Comment by vinaygaba** [comment]
Accepted your pull request and closing this issue. Really appreciate your contribution! Thank you.
